name: to_do_app
description: "Super TODO app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.7
  realm: ^2.2.1
  flutter_iconpicker: ^3.4.6
  flutter_colorpicker: ^1.0.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_bloc: ^8.1.5
  firebase_database: ^10.5.7
  rxdart: ^0.27.7
  date_picker_timeline: ^1.2.6

  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
      - assets/images/
      - assets/translations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-Hairline.ttf
        - asset: assets/fonts/Lato/Lato-Heavy.ttf
          weight: 200
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Medium.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Semibold.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 300
