class Constants {
  static String emailRegex =
      r"^[a-zA-Z0-9.a-zA-Z0-9.!#$%&'*+-/=?^_`{|}~]+@[a-zA-Z0-9]+\.[a-zA-Z]+";
  static String settingIcon = "assets/images/ic_settings.png";
  static String profileIcon = "assets/images/ic_profile.png";
  static String homeIcon = "assets/images/ic_home.png";
  static String passwordIcon = "assets/images/ic_password.png";
  static String languageIcon = "assets/images/ic_language.png";
  static String themeIcon = "assets/images/ic_theme.png";
  static String photoIcon = "assets/images/ic_photo.png";
  static String typographyIcon = "assets/images/ic_typography.png";
  static String logoutIcon = "assets/images/ic_logout.png";
  static String todoIcon = "assets/images/ic_todo.png";
  static String splashIcon = "assets/images/ic_splash.png";
  static String onboardingPage1 = "assets/images/icon_onboarding_1.png";
  static String onboardingPage2 = "assets/images/icon_onboarding_2.png";
  static String onboardingPage3 = "assets/images/icon_onboarding_3.png";
  static String faqIcon = "assets/images/ic_faq.png";
  static String aboutUsIcon = "assets/images/ic_about_us.png";
  static String helpAndFeedbackIcon = "assets/images/ic_help_and_feedback.png";
  static String buyMeACoffeeIcon = "assets/images/ic_buy_me_a_coffee.png";
  static String importIcon = "assets/images/ic_import.png";
  static String sendIcon = "assets/images/ic_send.png";
  static String closeIcon = "assets/images/ic_close.png";
  static String deleteIcon = "assets/images/ic_delete.png";
  static String editIcon = "assets/images/ic_edit.png";
  static String subTaskIcon = "assets/images/ic_sub_task.png";
  static String taskCategoryIcon = "assets/images/ic_task_category.png";
  static String taskPriorityIcon = "assets/images/ic_task_priority.png";
  static String taskTimeIcon = "assets/images/ic_task_time.png";
  static int primaryColor = 0xff8687E7;
}
